[package]
name = "validatron"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.53"
log = "0.4"
thiserror = "1.0.30"
validatron-derive = {path = "derive"}