[package]
name = "test-suite"
version = "0.4.0"
license = "Apache-2.0"
edition = "2021"


[dependencies]
file-system-monitor = { path = "../modules/file-system-monitor", features = ["test-suite"] }
network-monitor = { path = "../modules/network-monitor", features = ["test-suite"] }
process-monitor = { path = "../modules/process-monitor", features = ["test-suite"] }
libtest-mimic =  "0.6.0"
bpf-common = { path = "../bpf-common", features = ["test-utils", "test-suite"] }
tokio = { version = "1", features = ["full"] }
log = { version = "0.4", features = ["std"] }
futures = "0.3.21"
