[package]
name = "rules-engine"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
validatron = { path = "../../validatron" }
pulsar-core = { path = "../../pulsar-core" }

log = "0.4.17"
anyhow = "1"
tokio = "1.15.0"
glob = "0.3.1"
thiserror = "1.0.40"
serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"
lalrpop-util = { version="0.19.9", features=["lexer"] }
async-trait = "0.1.73"

[build-dependencies]
lalrpop = "0.19.9"
